In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("C:/Users/LENOVO/Desktop/MY PROJECTS/AI reccomendation project/internship_data.csv")

In [4]:
df

,id,title,organization,domain,skills,location,duration_weeks,eligibility,mode,description,source
0,INT001,Data Analysis Intern,Ministry of Education,Data Science,Python;Excel;Statistics,Remote,8,Undergraduate,Remote,Analyze education datasets for policy insights,PM Internship Portal
1,INT002,AI Research Intern,MeitY,AI & ML,Python;ML;Deep Learning,Remote,12,Postgraduate,Remote,Assist in AI research and model development,PM Internship Portal
2,INT003,Web Development Intern,Ministry of Tourism,Web Development,HTML;CSS;JavaScript,Delhi,8,Undergraduate,Onsite,Develop and maintain tourism portals,PM Internship Portal
3,INT004,Cybersecurity Intern,CERT-In,Cybersecurity,Networking;Linux;Security,Delhi,12,Postgraduate,Onsite,Assist in cyber threat analysis,PM Internship Portal
4,INT005,Policy Research Intern,NITI Aayog,Public Policy,Research;MS Word;Data Analysis,Delhi,10,Postgraduate,Onsite,Policy evaluation and report drafting,PM Internship Portal
...,...,...,...,...,...,...,...,...,...,...,...
85,INT086,AI in Education Intern,UGC,EdTech AI,ML;Education Data,Delhi,8,Postgraduate,Onsite,AI for learning outcomes,PM Internship Portal
86,INT087,Logistics Analytics Intern,Ministry of Defence,Operations Analytics,Optimization;Excel,Delhi,10,Postgraduate,Onsite,Defense logistics optimization,PM Internship Portal
87,INT088,Open Source Intern,MeitY,Open Source,Git;Linux;Python,Remote,8,Undergraduate,Remote,Contribute to gov OSS projects,PM Internship Portal
88,INT089,Speech Recognition Intern,ISRO,AI & ML,Speech Processing;Python,Bangalore,12,Postgraduate,Onsite,Voice-based control systems,PM Internship Portal
89,INT090,Data Product Intern,NIC,Data Products,Product Thinking;Analytics,Remote,8,Undergraduate,Remote,Build data-driven gov products,PM Internship Portal

In [5]:
#columns to use-title,domain,skills,description
df.copy()

,id,title,organization,domain,skills,location,duration_weeks,eligibility,mode,description,source
0,INT001,Data Analysis Intern,Ministry of Education,Data Science,Python;Excel;Statistics,Remote,8,Undergraduate,Remote,Analyze education datasets for policy insights,PM Internship Portal
1,INT002,AI Research Intern,MeitY,AI & ML,Python;ML;Deep Learning,Remote,12,Postgraduate,Remote,Assist in AI research and model development,PM Internship Portal
2,INT003,Web Development Intern,Ministry of Tourism,Web Development,HTML;CSS;JavaScript,Delhi,8,Undergraduate,Onsite,Develop and maintain tourism portals,PM Internship Portal
3,INT004,Cybersecurity Intern,CERT-In,Cybersecurity,Networking;Linux;Security,Delhi,12,Postgraduate,Onsite,Assist in cyber threat analysis,PM Internship Portal
4,INT005,Policy Research Intern,NITI Aayog,Public Policy,Research;MS Word;Data Analysis,Delhi,10,Postgraduate,Onsite,Policy evaluation and report drafting,PM Internship Portal
...,...,...,...,...,...,...,...,...,...,...,...
85,INT086,AI in Education Intern,UGC,EdTech AI,ML;Education Data,Delhi,8,Postgraduate,Onsite,AI for learning outcomes,PM Internship Portal
86,INT087,Logistics Analytics Intern,Ministry of Defence,Operations Analytics,Optimization;Excel,Delhi,10,Postgraduate,Onsite,Defense logistics optimization,PM Internship Portal
87,INT088,Open Source Intern,MeitY,Open Source,Git;Linux;Python,Remote,8,Undergraduate,Remote,Contribute to gov OSS projects,PM Internship Portal
88,INT089,Speech Recognition Intern,ISRO,AI & ML,Speech Processing;Python,Bangalore,12,Postgraduate,Onsite,Voice-based control systems,PM Internship Portal
89,INT090,Data Product Intern,NIC,Data Products,Product Thinking;Analytics,Remote,8,Undergraduate,Remote,Build data-driven gov products,PM Internship Portal

In [6]:
main_df=df.drop(['id','organization','location','duration_weeks','eligibility','mode','source'],axis=1)
main_df.copy()

,title,domain,skills,description
0,Data Analysis Intern,Data Science,Python;Excel;Statistics,Analyze education datasets for policy insights
1,AI Research Intern,AI & ML,Python;ML;Deep Learning,Assist in AI research and model development
2,Web Development Intern,Web Development,HTML;CSS;JavaScript,Develop and maintain tourism portals
3,Cybersecurity Intern,Cybersecurity,Networking;Linux;Security,Assist in cyber threat analysis
4,Policy Research Intern,Public Policy,Research;MS Word;Data Analysis,Policy evaluation and report drafting
...,...,...,...,...
85,AI in Education Intern,EdTech AI,ML;Education Data,AI for learning outcomes
86,Logistics Analytics Intern,Operations Analytics,Optimization;Excel,Defense logistics optimization
87,Open Source Intern,Open Source,Git;Linux;Python,Contribute to gov OSS projects
88,Speech Recognition Intern,AI & ML,Speech Processing;Python,Voice-based control systems
89,Data Product Intern,Data Products,Product Thinking;Analytics,Build data-driven gov products

In [7]:
main_df["profile_text"] = (
    main_df["title"] + " " +
    main_df["domain"] + " " +
    main_df["skills"].str.replace(";", " ") + " " +
    main_df["description"]
)

In [8]:
main_df

,title,domain,skills,description,profile_text
0,Data Analysis Intern,Data Science,Python;Excel;Statistics,Analyze education datasets for policy insights,Data Analysis Intern Data Science Python Excel...
1,AI Research Intern,AI & ML,Python;ML;Deep Learning,Assist in AI research and model development,AI Research Intern AI & ML Python ML Deep Lear...
2,Web Development Intern,Web Development,HTML;CSS;JavaScript,Develop and maintain tourism portals,Web Development Intern Web Development HTML CS...
3,Cybersecurity Intern,Cybersecurity,Networking;Linux;Security,Assist in cyber threat analysis,Cybersecurity Intern Cybersecurity Networking ...
4,Policy Research Intern,Public Policy,Research;MS Word;Data Analysis,Policy evaluation and report drafting,Policy Research Intern Public Policy Research ...
...,...,...,...,...,...
85,AI in Education Intern,EdTech AI,ML;Education Data,AI for learning outcomes,AI in Education Intern EdTech AI ML Education ...
86,Logistics Analytics Intern,Operations Analytics,Optimization;Excel,Defense logistics optimization,Logistics Analytics Intern Operations Analytic...
87,Open Source Intern,Open Source,Git;Linux;Python,Contribute to gov OSS projects,Open Source Intern Open Source Git Linux Pytho...
88,Speech Recognition Intern,AI & ML,Speech Processing;Python,Voice-based control systems,Speech Recognition Intern AI & ML Speech Proce...
89,Data Product Intern,Data Products,Product Thinking;Analytics,Build data-driven gov products,Data Product Intern Data Products Product Thin...

In [9]:
#TF-IDF text-vector
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(
        stop_words='english',
        max_features=5000
)
tfidf_matrix = vectorizer.fit_transform(main_df["profile_text"])

In [10]:
print(tfidf_matrix.shape)

(90, 337)

In [11]:
#Recommendation Code 
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(tfidf_matrix)

In [12]:
def internship_recommendation(user_entry,top_n=5):
    query_vector = vectorizer.transform([user_entry]) #Convert user text into vector
    similarity_scores = cosine_similarity(query_vector, tfidf_matrix)[0]  #Compare user vector with all internships
    top_indices=similarity_scores.argsort()[::-1][:top_n]  #this skip 1.0(itself) from recommendation
    return df.iloc[top_indices]

In [13]:
print(internship_recommendation('Data Science')[["title", "organization", "domain"]])

                      title           organization                 domain
0      Data Analysis Intern  Ministry of Education           Data Science
77      Climate Data Intern                    IMD        Climate Science
24  Climate Research Intern                 MoEFCC  Environmental Science
37      Data Quality Intern                  UIDAI        Data Governance
71  Data Warehousing Intern                  MoSPI       Data Engineering